# Generated by Django 5.0.2 on 2024-02-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
